### ISSUE TITLE
Doesn't work with leiningen 2.8.1

### ISSUE THREAD

**Issue by SevereOverfl0w** [kkinnear/lein-zprint#2]
Happens with both `[lein-zprint "0.3.3"]` and `[lein-zprint "0.3.4"]` on command `lein zprint :lumo-cmd-line ~/.cache/zprint`

```
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate trptcolin/versioneer/core__init.class or trptcolin/versioneer/core.clj on classpath., compiling:(leiningen/zprint.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7391)
    clojure.lang.RT.loadResourceScript (RT.java:372)
    clojure.lang.RT.loadResourceScript (RT.java:363)
    clojure.lang.RT.load (RT.java:453)
    clojure.lang.RT.load (RT.java:419)
    clojure.core$load$fn__5677.invoke (core.clj:5893)
    clojure.core$load.invokeStatic (core.clj:5892)
    clojure.core$load.doInvoke (core.clj:5876)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invokeStatic (core.clj:5697)
    clojure.core$load_one.invoke (core.clj:5692)
    clojure.core$load_lib$fn__5626.invoke (core.clj:5737)
    clojure.core$load_lib.invokeStatic (core.clj:5736)
    clojure.core$load_lib.doInvoke (core.clj:5717)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$load_libs.invokeStatic (core.clj:5774)
    clojure.core$load_libs.doInvoke (core.clj:5758)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$require.invokeStatic (core.clj:5796)
    clojure.core$require.doInvoke (core.clj:5796)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    leiningen.core.utils$require_resolve.invokeStatic (utils.clj:102)
    leiningen.core.utils$require_resolve.invoke (utils.clj:95)
    leiningen.core.utils$require_resolve.invokeStatic (utils.clj:105)
    leiningen.core.utils$require_resolve.invoke (utils.clj:95)
    leiningen.core.main$lookup_task_var.invokeStatic (main.clj:69)
    leiningen.core.main$lookup_task_var.invoke (main.clj:65)
    leiningen.core.main$pass_through_help_QMARK_.invokeStatic (main.clj:79)
    leiningen.core.main$pass_through_help_QMARK_.invoke (main.clj:73)
    leiningen.core.main$task_args.invokeStatic (main.clj:82)
    leiningen.core.main$task_args.invoke (main.clj:81)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:339)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__4734.invoke (main.clj:420)
    leiningen.core.main$_main.invokeStatic (main.clj:411)
    leiningen.core.main$_main.doInvoke (main.clj:408)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:482)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate trptcolin/versioneer/core__init.class or trptcolin/versioneer/core.clj on classpath.
 at clojure.lang.RT.load (RT.java:456)
    clojure.lang.RT.load (RT.java:419)
    clojure.core$load$fn__5677.invoke (core.clj:5893)
    clojure.core$load.invokeStatic (core.clj:5892)
    clojure.core$load.doInvoke (core.clj:5876)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invokeStatic (core.clj:5697)
    clojure.core$load_one.invoke (core.clj:5692)
    clojure.core$load_lib$fn__5626.invoke (core.clj:5737)
    clojure.core$load_lib.invokeStatic (core.clj:5736)
    clojure.core$load_lib.doInvoke (core.clj:5717)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$load_libs.invokeStatic (core.clj:5774)
    clojure.core$load_libs.doInvoke (core.clj:5758)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$require.invokeStatic (core.clj:5796)
    clojure.core$require.doInvoke (core.clj:5796)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    leiningen.zprint$eval494$loading__5569__auto____495.invoke (zprint.clj:1)
    leiningen.zprint$eval494.invokeStatic (zprint.clj:1)
    leiningen.zprint$eval494.invoke (zprint.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6927)
    clojure.lang.Compiler.eval (Compiler.java:6916)
    clojure.lang.Compiler.load (Compiler.java:7379)
    clojure.lang.RT.loadResourceScript (RT.java:372)
    clojure.lang.RT.loadResourceScript (RT.java:363)
    clojure.lang.RT.load (RT.java:453)
    clojure.lang.RT.load (RT.java:419)
    clojure.core$load$fn__5677.invoke (core.clj:5893)
    clojure.core$load.invokeStatic (core.clj:5892)
    clojure.core$load.doInvoke (core.clj:5876)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invokeStatic (core.clj:5697)
    clojure.core$load_one.invoke (core.clj:5692)
    clojure.core$load_lib$fn__5626.invoke (core.clj:5737)
    clojure.core$load_lib.invokeStatic (core.clj:5736)
    clojure.core$load_lib.doInvoke (core.clj:5717)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$load_libs.invokeStatic (core.clj:5774)
    clojure.core$load_libs.doInvoke (core.clj:5758)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$require.invokeStatic (core.clj:5796)
    clojure.core$require.doInvoke (core.clj:5796)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    leiningen.core.utils$require_resolve.invokeStatic (utils.clj:102)
    leiningen.core.utils$require_resolve.invoke (utils.clj:95)
    leiningen.core.utils$require_resolve.invokeStatic (utils.clj:105)
    leiningen.core.utils$require_resolve.invoke (utils.clj:95)
    leiningen.core.main$lookup_task_var.invokeStatic (main.clj:69)
    leiningen.core.main$lookup_task_var.invoke (main.clj:65)
    leiningen.core.main$pass_through_help_QMARK_.invokeStatic (main.clj:79)
    leiningen.core.main$pass_through_help_QMARK_.invoke (main.clj:73)
    leiningen.core.main$task_args.invokeStatic (main.clj:82)
    leiningen.core.main$task_args.invoke (main.clj:81)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:339)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__4734.invoke (main.clj:420)
    leiningen.core.main$_main.invokeStatic (main.clj:411)
    leiningen.core.main$_main.doInvoke (main.clj:408)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:482)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

**Comment by kkinnear** [comment]
So far, I can't reproduce this problem.  I took versioneer out last March.  I can't make this happen with any combination of project.clj files and versions of lein-zprint or zprint.  Any chance you could share your project.clj? Or at least enough of it to cause this problem?  Thanks!

**Comment by SevereOverfl0w** [comment]
I don't think you fully took it out, I see this line: https://github.com/kkinnear/lein-zprint/blob/master/src/leiningen/zprint.clj#L4

Could this be related to my leiningen version? I'm using 2.8.1. My project.clj is very simple (I'm piggiebacking on the aero one!)

```
;; Copyright © 2015, JUXT LTD.

(defproject aero "1.1.2"
  :description "A small library for explicit, intentful configuration."
  :url "http://github.com/juxt/aero"
  :license {:name "The MIT License"
            :url "http://opensource.org/licenses/MIT"}
  :dependencies []
  :plugins [[lein-shell "0.5.0"]
            [lein-zprint "0.3.4"]]

  :aliases {"test" ["do" ["test"] ["shell" "./lumo-test"]]}
  :profiles {:dev {:dependencies [[org.clojure/clojure "1.8.0"]]}})
```

**Comment by kkinnear** [comment]
You are correct on both counts!  I thought I grepped for versioneer everywhere, but obviously I didn't.  And for reasons that I haven't yet figured out, this works ok with older versions of leiningen (at least in my environment), but fails with 2.8.1.  I should have upgraded immediately, didn't think it would matter.  Thanks much!  I'll release a new version this weekend.  Nothing in lein zprint works with leiningen 2.8.1.

**Comment by kkinnear** [comment]
I'm working on this.  It isn't as simple as fixing my screwup with versioneer.  Leiningen has changed as well in 2.8.1, so the `:lumo-cmd-line` and `:planck-cmd-line` capabilities don't work anymore.  I would just have dropped them, because of the existence of the zprint-filter over in zprint, but the original issue here was to get `:lumo-cmd-line` to work, so that seems a bit harsh.

The fix for the short term is to downgrade leiningen:

`lein upgrade 2.7.1`

will get you a version which will work correctly.  I'm working on getting the `:lumo-cmd-line` and `:planck-cmd-line` capability working again.  If I can't do that by Saturday afternoon Nov 11, I'll release a new `lein-zprint` version that at least works with leiningen 2.8.1 for formatting files, and continue to work on the `*-cmd-line` capability without preventing folks from formatting their files with leiningen 2.8.1.

**Comment by SevereOverfl0w** [comment]
Your target output is quite simple if I'm right?

lumo -cp classpath -k ~/.cache-dir

A few ideas I have:
- Generate them into releases on the zprint repo using `boot with-cp ...`
- tools.deps.alpha probably has similar functionality at this time

I actually find this part of the lein plugin quite tedious, as I want the command line without adding the plugin to an arbitrary project.clj just to dump it out.

On 11 November 2017 01:54:06 GMT+00:00, Kim Kinnear <notifications@github.com> wrote:
>I'm working on this.  It isn't as simple as fixing my screwup with
>versioneer.  Leiningen has changed as well in 2.8.1, so the
>`:lumo-cmd-line` and `:planck-cmd-line` capabilities don't work
>anymore.  I would just have dropped them, because of the existence of
>the zprint-filter over in zprint, but the original issue here was to
>get `:lumo-cmd-line` to work, so that seems a bit harsh.
>
>The fix for the short term is to downgrade leiningen:
>
>`lein upgrade 2.7.1`
>
>will get you a version which will work correctly.  I'm working on
>getting the `:lumo-cmd-line` and `:planck-cmd-line` capability working
>again.  If I can't do that by Saturday afternoon Nov 11, I'll release a
>new `lein-zprint` version that at least works with leiningen 2.8.1 for
>formatting files, and continue to work on the `*-cmd-line` capability
>without preventing folks from formatting their files with leiningen
>2.8.1.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kkinnear/lein-zprint/issues/2#issuecomment-343631321

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kkinnear** [comment]
Thanks a lot for the pull request!  As I said in the review, I had found a way to get the classpath as a seq of strings from leiningen, but your fix was less work and a smaller change as well, so I went with that.  I really appreciate it. 

On the larger subject of how to generate this command line without having to install a version of lein-zprint into some random project.  There are two issues, as you clearly know: first, getting the dependencies downloaded, and second, finding them and spitting out the command line.  I believe that you were referencing tools.deps.alpha as a way to get the dependencies downloaded and, I presume, loaded.  I've listened to Alex's talk about this, and looked at tools.deps.alpha briefly, and I suspect that you are right.  There is probably a way to download the dependencies and find where they are and generate this command line w/out having to use a leiningen plugin.  I agree, having something -- probably a script and some associated code in zprint -- to generate this command line would be moderately nicer than installing lein-zprint into a project just to get the command line out.

Though I'm wondering if you'd have to install Clojure itself to get this to work with tools.deps.alpha  independent of leiningen.  Which, while not hard, might create about the same friction as editing a project.clj to generate this string.  But perhaps that wouldn't be necessary or it is less to do.  You are a good judge of that, since you are doing this regularly.

In any case, if you would be interested in taking on this work, I'd be delighted to distribute it with zprint!  Were you to take this on, it would be good to have a brief discussion of where the code would go in zprint itself.  My first thought would be to put the code in main.cljc, which presently takes an options map as its only command line argument.  I would suggest taking a keyword like `:lumo-cmd-line` or something instead of a map to generate the command-line.  The main.cljc file (and thus the zprint.main namespace) shows up in the regular jar file, so you could put the necessary code there.  

Thanks again for the pull request!

**Comment by SevereOverfl0w** [comment]
I hadn't realized you were pulling only the `rewrite-cljs` dependency at the time I wrote that. The fetching part puts a spanner in most of my ideas around reducing effort unfortunately.

Lumo & Planck have gained the switches `-d` to add a dependency via maven coordinates, e.g. `lumo -D rewrite-cljs:0.4.4 -D zprint:0.4.4 -m zprint.lumo` works for example.

So the real tasks become:
- Get rewrite-cljs version
- Get zprint & rewrite-cljs jar.

It's possible that https://github.com/eginez/huckleberry could be built into a script though, dependent on how fast it is.

One thing might be to just simplify it with a boot version of this script e.g. lein new (boot-new) equivalent is a dependency, but can be run outside of a project, without modifying any files:

```
boot -d boot/new new -t app -n myapp
```

I shall give this some further thought and see if I come up with something impressive, particularly around the next zprint upgrade I perform I suspect 😛

**Comment by kkinnear** [comment]
The -d switch is nice, so we don't have know where it is locally.  Getting the zprint and rewrite-cljs jar files is really the only part that needs to be done.  

I wouldn't have a problem updating the rewrite-cljs version in a script whenever I change it (since I don't change it often).  It could be hard-coded into a script.  Alternatively, we could have a script which I run when I release things which would get the rewrite-cljs version from project.clj directly (grep and sed or whatever) and outputs a second script to put in the release for zprint.  There is no particular reason to have to figure out the rewrite-cljs version on the target system.

So, if you can figure out how to get the jars given their names, in a way that is easy for folks, the rest seems straightforward.

**Comment by SevereOverfl0w** [comment]
I've discovered that this works from anywhere to fetch dependencies: `echo "" | lein update-in :dependencies conj '[zprint "RELEASE"]' -- repl`

I couldn't find another command which fetched dependencies *AND* worked outside of the context of a project.

It would be nice if the script somehow knew whether it needed to fetch the dependencies or not. However, compromising that, we can do something along the lines of: `./script init`.

**Comment by kkinnear** [comment]
Wow, that's not something that I wold have come up with from scratch.  

I'm not sure what you are implying with `./script init`.  That you say "init" if you want it to get the dependencies?  That works.  

Alternatively, what do lumo and planck do if the dependencies that one specifies aren't there?  If they error out in some way, we might be able to work with that.  What about a script which tried to run them assuming the dependencies were there, and if they weren't, caught the error and fetched the dependencies like you show above, and then ran whichever of them successfully?  The first time you use it, maybe you get an error and a message that it is fetching dependencies, and then it works, and after that, it just works?

**Comment by SevereOverfl0w** [comment]
I tried the error case, lumo did not error. I haven't tried getting hold of planck for Linux yet, so did not test that.

On 13 November 2017 01:26:14 GMT+00:00, Kim Kinnear <notifications@github.com> wrote:
>Wow, that's not something that I wold have come up with from scratch.  
>
>I'm not sure what you are implying with `./script init`.  That you say
>"init" if you want it to get the dependencies?  That works.  
>
>Alternatively, what do lumo and planck do if the dependencies that one
>specifies aren't there?  If they error out in some way, we might be
>able to work with that.  What about a script which tried to run them
>assuming the dependencies were there, and if they weren't, caught the
>error and fetched the dependencies like you show above, and then ran
>whichever of them successfully?  The first time you use it, maybe you
>get an error and a message that it is fetching dependencies, and then
>it works, and after that, it just works?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kkinnear/lein-zprint/issues/2#issuecomment-343786348

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
