### ISSUE TITLE
Support all the switches?

### ISSUE THREAD

**Issue by pfernandez** [kkinnear/lein-zprint#8]
Hi there, thanks for the fantastic work!

I'd like to use lein-zprint (rather than a standalone binary) so that it can be run automatically with a git hook or in CI without needing a separate installation step. That way we can enforce formatting without worrying about everyone's personal setup, and they can install a binary only if desired.

Unfortunately the commandline flags don't seem to be supported:

```
14:55 $ lein zprint -lfsw *.clj
java.lang.Exception: Unknown switch '-lfsw'
 at leiningen.zprint$get_switch.invokeStatic (zprint.clj:116)
 ...
```

The `-c` flag would also be nice to have. :)

**Comment by kkinnear** [comment]
Yes, the leiningen binary and the uberjar (and standalone binaries) are different pieces of code.  They both use the basic zprint library, but are otherwise different (though similar) pieces of code.  The `lein zprint` code predates the uberjar code by several years.

The current `lien zprint` code and reporting is more or less like `-lw` in the prebuilt binaries.

What specifically are you wanting that I might be able to add to `lien zprint`?  It sounds like `-c`.   

I'm torn between trying to extend `lein zprint` to process a few more switches that you need and adding some kind of call-out to the uberjar code that is already there.  Depends I think on what you want.  Things like `-s` and `-f` are probably pretty easy to add to `lein zprint`.  Possibly `-c` as well.  

I'm open to doing something to get you what you want, once I know in more detail what it is.

Thanks!

**Comment by pfernandez** [comment]
Thanks so much for the reply. I'd specifically like to replace cljfmt in the following lines in our makefiles:

```make
# Runs style checker
static/fmt-check:
  @ lein cljfmt check

# Runs style checker and fixes issues
static/fmt-fix:
  @ lein cljfmt fix
```

I think to replace that first command I'd need `lein zprint -c` or some other way to do a dry run.

**Comment by kkinnear** [comment]
I'll look at adding a `-c` switch to `lein zprint`.  It doesn't look too bad, but you never know...

**Comment by kkinnear** [comment]
I have the basics implemented, but I'm wondering how you interpret the output?  For the pre-built binaries, I emit the number of incorrectly formatted files as the exit status.  Thus, it exits successfully when they are all formatted correctly.  

I can't figure out how to do that in leiningen.  I looked at cljfmt, and it looks like it output messages to `stderr` if some files are not formatted correctly, otherwise the messages come out to `stdout`.

What do you want done?

Here is what it does now, all to `stdout`:
```
projects/zprint % lein zprint -c proj.clj
Processing file: proj.clj
File: proj.clj was incorrectly formatted
1 file formatted incorrectly
√ projects/zprint % lein zprint proj.clj
Processing file: proj.clj
√ projects/zprint % lein zprint -c proj.clj
Processing file: proj.clj
All files formatted correctly.
```

**Comment by pfernandez** [comment]
I can’t believe you’ve already implemented this. Thank you! I would suggest following the example of cljfmt so that it will work as a drop-in replacement in our (and other’s) CI pipelines. 

This is a side question/observation, but it seems that the only way to override user config (or even to use a separate config file) is to add a directive in their personal project.clj. The problem with this is that people are resistant to change, and it creates friction by requiring everyone to add a personal config file.

I’m just returning to Clojure after a few years in the NPM ecosystem, and the standard pattern there (i.e. with Prettier) is for config files to have “depth-first” priority by default so that formatting just works in different projects while remaining transparent to the user. Maybe setting ‘:search-config true’ in project.clj could accomplish this while preserving backward compatibility?

**Comment by kkinnear** [comment]
I'm confused by your side question.  I hear that you want to override user config, but to do that everyone has to add a personal config file?  That doesn't make any sense to me, so I'm not getting something here. I would like to fix the problem, but I'm still up in the air as to what the problem is.

I can say that, with recent versions of lein-zprint, you can indeed set `:search-config? true` in the `:zprint` key in your `project.clj`.  So that if there is a `.zprintrc` or `.zprint.edn` file in the project, it will get looked at.

I guess I'm confused as to what zprint configuration you want to have take precedence?  The user's personal `~/.zprintrc` has the least precedence.  Next is any local `.zprintrc` or `.zprint.edn` files, and then the `:zprint` key in the `project.clj`, and then any options from the actual line containing `lein zprint`.  The `:zprint` key in the `project.clj` file is examined for `:search-config? true` before the other configuration options it contains are used.

But all of that may or may not be interesting.  I'd love to learn the details of what isn't working for you, if you wouldn't mind explaining in more detail.  Thanks!

**Comment by pfernandez** [comment]
> with recent versions of lein-zprint, you can indeed set :search-config? true in the :zprint key in your project.clj

> The user's personal ~/.zprintrc has the least precedence. Next is any local .zprintrc or .zprint.edn files, and then the :zprint key in the project.clj, and then any options from the actual line containing lein zprint. The :zprint key in the project.clj file is examined for :search-config? true before the other configuration options it contains are used.

This is exactly the behavior I had wanted/expected. Thanks for clarifying. I had been following the [configuration section](https://github.com/kkinnear/lein-zprint#to-configure-lein-zprint-in-its-normal-highly-configurable-way) of the readme, but now I see that you describe using `:search-config? true` in project.clj further down the page. I'll give it a try to be sure, but it sounds good.

**Comment by kkinnear** [comment]
In release `1.2.4` you now have the `-c` switch.  It also exits with non-zero exit-status if any of them do not "check" correctly.  Try `lein zprint :help` for a bit more information.

**Comment by pfernandez** [comment]
Perfect, thanks!

**Comment by kkinnear** [comment]
I wish it were perfect.  Unfortunately, I had a dependency on a alpha version of zprint in the `1.2.4` version of `lein-zprint`.  I have just fixed it so that now there is a `1.2.4.1` version of `lein-zprint`, which should actually work.  Sorry about that!

**Comment by pfernandez** [comment]
No worries, I've had to finish up a project before coming back to this anyway. I'll let you know how it goes. 😄

**Comment by pfernandez** [comment]
Well, I finally was given some time to work on tech debt and got this into our project. It works perfectly as a drop-in replacement for clj-fmt and everyone seems happy. I've added it as a pre-commit hook to make sure everyone uses it, and for myself I use the cli version to format on save with Vim.

Thanks again!
